### ISSUE TITLE
Android: Execution failed for task ':react-native-audio-playback:compileDebugKotlin'.

### ISSUE THREAD

**Issue by Akash-Pavithran** [itsramiel/react-native-audio-playback#21]
"react-native": "0.72.6",
"react-native-audio-playback": "1.0.4",

Issue:  Unable to run the app in Android. When i run `npm run android` i get this error

```info JS server already running.
info Installing the app...

> Configure project :react-native-reanimated
Android gradle plugin: 7.4.2
Gradle: 8.0.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Task :react-native-audio-playback:compileDebugKotlin
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.

> Task :react-native-audio-playback:compileDebugKotlin FAILED

> Task :react-native-gesture-handler:compileDebugKotlin
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
w: D:\Projects\React Native\OddOrEven\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\core\GestureHandler.kt: (770, 11): Name shadowed: size
w: D:\Projects\React Native\OddOrEven\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEnabledRootView.kt: (9, 51): Unreachable code
w: D:\Projects\React Native\OddOrEven\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEnabledRootView.kt: (10, 80): Unreachable code
w: D:\Projects\React Native\OddOrEven\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootHelper.kt: (80, 18): 'onChildStartedNativeGesture(MotionEvent!): Unit' is deprecated. Deprecated in Java
w: D:\Projects\React Native\OddOrEven\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootHelper.kt: (86, 42): Parameter 'disallowIntercept' is never used
w: D:\Projects\React Native\OddOrEven\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootHelper.kt: (118, 28): Parameter 'viewTag' is never used
w: D:\Projects\React Native\OddOrEven\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerTouchEvent.kt: (7, 44): 'RCTEventEmitter' is deprecated. Deprecated in Java
w: D:\Projects\React Native\OddOrEven\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerTouchEvent.kt: (14, 11): 'init(Int): Unit' is deprecated. Deprecated in Java
w: D:\Projects\React Native\OddOrEven\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerTouchEvent.kt: (30, 42): 'RCTEventEmitter' is deprecated. Deprecated in Java
w: D:\Projects\React Native\OddOrEven\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerTouchEvent.kt: (31, 21): 'receiveEvent(Int, String!, WritableMap?): Unit' is deprecated. Deprecated in Java
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
122 actionable tasks: 9 executed, 113 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (17, 8): Unresolved reference: kotlinx
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (18, 8): Unresolved reference: kotlinx
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (19, 8): Unresolved reference: kotlinx
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (20, 8): Unresolved reference: kotlinx
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (107, 7): Unresolved reference: CoroutineScope
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (107, 22): Unresolved reference: Dispatchers
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (108, 9): Unresolved reference: withContext
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (108, 21): Unresolved reference: Dispatchers

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-audio-playback:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

Before installing the library it was building successful in android. Im not sure if similar issue is in iOS and currently im using a windows.
There are no code snippets as build started failing right after installing the package.

**Comment by itsramiel** [comment]
Please provide the entire error log

**Comment by itsramiel** [comment]
I have a hunch that it is because your app is not setup to work with Kotlin, but I am not sure. Anyways please also provide a reproducible.

**Comment by Akash-Pavithran** [comment]
This is the complete log i could get

```

> Configure project :react-native-reanimated
Android gradle plugin: 7.4.2
Gradle: 8.0.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Task :react-native-audio-playback:compileDebugKotlin
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.

> Task :react-native-audio-playback:compileDebugKotlin FAILED

> Task :react-native-svg:compileDebugJavaWithJavac

> Task :react-native-screens:compileDebugKotlin
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.kt:87:22 'constructor GuardedRunnable(ReactContext!)' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt:65:28 'setter for targetElevation: Float' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt:128:28 'setter for targetElevation: Float' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:86:34 'getter for systemWindowInsetTop: Int' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:229:37 'setColorFilter(Int, PorterDuff.Mode): Unit' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:65:22 'constructor GuardedRunnable(ReactContext!)' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:110:22 'constructor GuardedRunnable(ReactContext!)' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:137:47 'replaceSystemWindowInsets(Int, Int, Int, Int): WindowInsetsCompat' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:138:51 'getter for systemWindowInsetLeft: Int' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:140:51 'getter for systemWindowInsetRight: Int' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:141:51 'getter for systemWindowInsetBottom: Int' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt:100:22 Parameter 'view' is never used
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt:100:43 Parameter 'placeholder' is never used
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarView.kt:147:43 Parameter 'flag' is never used
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/HeaderHeightChangeEvent.kt:5:44 'RCTEventEmitter' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/HeaderHeightChangeEvent.kt:10:5 'constructor Event<T : Event<(raw) Event<*>>!>(Int)' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/HeaderHeightChangeEvent.kt:17:44 'RCTEventEmitter' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/HeaderHeightChangeEvent.kt:20:25 'receiveEvent(Int, String!, WritableMap?): Unit' is deprecated. Deprecated in Java
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:42 Parameter 'width' is never used
w: file:///D:/Projects/React%20Native/OddOrEven/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:54 Parameter 'height' is never used
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
139 actionable tasks: 12 executed, 127 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (17, 8): Unresolved reference: kotlinx
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (18, 8): Unresolved reference: kotlinx
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (19, 8): Unresolved reference: kotlinx
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (20, 8): Unresolved reference: kotlinx
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (107, 7): Unresolved reference: CoroutineScope
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (107, 22): Unresolved reference: Dispatchers
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (108, 9): Unresolved reference: withContext
e: D:\Projects\React Native\OddOrEven\node_modules\react-native-audio-playback\android\src\main\java\com\audioplayback\AudioPlaybackModule.kt: (108, 21): Unresolved reference: Dispatchers
Note: D:\Projects\React Native\OddOrEven\node_modules\react-native-svg\android\src\main\java\com\horcrux\svg\VirtualView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-audio-playback:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

```

**Comment by Akash-Pavithran** [comment]
> I have a hunch that it is because your app is not setup to work with Kotlin, but I am not sure. Anyways please also provide a reproducible.

If that is the issue, any tips to make the project support kotlin, The google suggetsion i got was to create native modules in kotlin

**Comment by Akash-Pavithran** [comment]
@itsramiel I've pushed a repo with the reproducible error
https://github.com/Akash-Pavithran/Native-RNAudioPlaybackIssue21

**Comment by itsramiel** [comment]
Hi @Akash-Pavithran. Sorry but this is not a minimal reproducible. You can install the library in a new react native project and check that it works. I ran the project you provided and there seems to be errors from other modules:

<img width="595" alt="Image" src="https://github.com/user-attachments/assets/b7dd7de5-bb58-4e74-a35f-88a88183a603" />

I can't debug the code for you. Please open an issue with a minimal reproducible(not lots of dependencies). Providing a repo and saying it doesnt work could mean a lot of things since you have an old react native project with many dependencies and configurations. I can just as easily provide you a repo and show you that it works. 

Please make it easier for me by providing a **minimal reproducible with a new react native project** reproducing the issue. It doesnt have to be the latest version of react native. You can initialize a new react native project with an old react native version to better match your environment.

**Comment by Akash-Pavithran** [comment]
@itsramiel Thank you for your response. I included the dependencies in my original repo to provide context in case there were any conflicts with other packages, as I thought that might help in troubleshooting. I understand now that a minimal reproducible example is preferred.

I've created a new minimal reproducible repo and am still encountering the error. Here’s the link to the[ minimal reproducible repo](https://github.com/Akash-Pavithran/RNAudioPlaybackBugRepro21/tree/main). Let me know if you need any additional details.

![Image](https://github.com/user-attachments/assets/52da6493-1db4-4f5b-ad4c-de1755810b2a)

**Comment by itsramiel** [comment]
Hi @Akash-Pavithran,

I checked the repo and yes I get what you are getting. I was able to support kotlin using the following:
```
diff --git a/android/app/build.gradle b/android/app/build.gradle
index 3f8372b..55f1631 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -1,4 +1,5 @@
 apply plugin: "com.android.application"
+apply plugin: "org.jetbrains.kotlin.android"
 apply plugin: "com.facebook.react"

 /**
diff --git a/android/build.gradle b/android/build.gradle
index 34ea718..51cf0ce 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -9,6 +9,7 @@ buildscript {

         // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
         ndkVersion = "23.1.7779620"
+        kotlinVersion = "2.0.21"
     }
     repositories {
         google()
@@ -17,5 +18,6 @@ buildscript {
     dependencies {
         classpath("com.android.tools.build:gradle")
         classpath("com.facebook.react:react-native-gradle-plugin")
+        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
     }
 }
```

But there was still some problems related to c++ and that is because of the ndk version used by this version of react native. Would you please try using the library with 0.73 and let me know if it works? With 0.73, kotlin is there by default and the ndk version is higher

**Comment by Akash-Pavithran** [comment]
@itsramiel I created a brand new project in RN 0.73 and tried building the project with the package and it throws a different error. This is a brand new project and kotlin is availbale by default and so i didnt make any changes in build.gradle files


```bash
> Task :react-native-audio-playback:buildCMakeDebug[arm64-v8a] FAILED
C/C++: ninja: Entering directory `D:\Projects\React Native\RN73\node_modules\react-native-audio-playback\android\.cxx\Debug\e2h91ip2\arm64-v8a'
C/C++: C:\Users\User\AppData\Local\Android\Sdk\ndk\25.1.8937393\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --sysroot=C:/Users/User/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dnative_lib_EXPORTS -I"D:/Projects/React Native/RN73/node_modules/react-native-audio-playback/android/src/main/cpp" -isystem C:/Users/User/.gradle/caches/transforms-3/ca7896164a9cb949a55e2600c990c30e/transformed/jetified-oboe-1.9.0/prefab/modules/oboe/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -std=gnu++17 -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/audio/NDKExtractor.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\audio\NDKExtractor.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/audio/NDKExtractor.cpp.o -c "D:/Projects/React Native/RN73/node_modules/react-native-audio-playback/android/src/main/cpp/audio/NDKExtractor.cpp"
C/C++: D:/Projects/React Native/RN73/node_modules/react-native-audio-playback/android/src/main/cpp/audio/NDKExtractor.cpp:21:10: fatal error: 'format' file not found
C/C++: #include <format>
C/C++:          ^~~~~~~~
C/C++: 1 error generated.
54 actionable tasks: 3 executed, 51 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-audio-playback:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `D:\Projects\React Native\RN73\node_modules\react-native-audio-playback\android\.cxx\Debug\e2h91ip2\arm64-v8a'
  [1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/audio/NDKExtractor.cpp.o
  FAILED: CMakeFiles/native-lib.dir/src/main/cpp/audio/NDKExtractor.cpp.o
  C:\Users\User\AppData\Local\Android\Sdk\ndk\25.1.8937393\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --sysroot=C:/Users/User/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dnative_lib_EXPORTS -I"D:/Projects/React Native/RN73/node_modules/react-native-audio-playback/android/src/main/cpp" -isystem C:/Users/User/.gradle/caches/transforms-3/ca7896164a9cb949a55e2600c990c30e/transformed/jetified-oboe-1.9.0/prefab/modules/oboe/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -std=gnu++17 -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/audio/NDKExtractor.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\audio\NDKExtractor.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/audio/NDKExtractor.cpp.o -c "D:/Projects/React Native/RN73/node_modules/react-native-audio-playback/android/src/main/cpp/audio/NDKExtractor.cpp"
  D:/Projects/React Native/RN73/node_modules/react-native-audio-playback/android/src/main/cpp/audio/NDKExtractor.cpp:21:10: fatal error: 'format' file not found
  #include <format>
           ^~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "D:\\Projects\\React Native\\RN73\\node_modules\\react-native-audio-playback\\android\\.cxx\\Debug\\e2h91ip2\\arm64-v8a" ^
        native-lib
    from D:\Projects\React Native\RN73\node_modules\react-native-audio-playback\android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 24s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':react-native-audio-playback:buildCMakeDebug[arm64-v8a]'. > com.android.ide.common.process.ProcessException: ninja: Entering directory `D:\Projects\React Native\RN73\node_modules\react-native-audio-playback\android\.cxx\Debug\e2h91ip2\arm64-v8a' [1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/audio/NDKExtractor.cpp.o FAILED: CMakeFiles/native-lib.dir/src/main/cpp/audio/NDKExtractor.cpp.o C:\Users\User\AppData\Local\Android\Sdk\ndk\25.1.8937393\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --sysroot=C:/Users/User/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dnative_lib_EXPORTS -I"D:/Projects/React Native/RN73/node_modules/react-native-audio-playback/android/src/main/cpp" -isystem C:/Users/User/.gradle/caches/transforms-3/ca7896164a9cb949a55e2600c990c30e/transformed/jetified-oboe-1.9.0/prefab/modules/oboe/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fno-limit-debug-info -fPIC -std=gnu++17 -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/audio/NDKExtractor.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\audio\NDKExtractor.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/audio/NDKExtractor.cpp.o -c "D:/Projects/React Native/RN73/node_modules/react-native-audio-playback/android/src/main/cpp/audio/NDKExtractor.cpp" D:/Projects/React Native/RN73/node_modules/react-native-audio-playback/android/src/main/cpp/audio/NDKExtractor.cpp:21:10: fatal error: 'format' file not found #include <format> ^~~~~~~~ 1 error generated. ninja: build stopped: subcommand failed. C++ build system [build] failed while executing: @echo off "C:\\Users\\User\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^ -C ^ "D:\\Projects\\React Native\\RN73\\node_modules\\react-native-audio-playback\\android\\.cxx\\Debug\\e2h91ip2\\arm64-v8a" ^ native-lib from D:\Projects\React Native\RN73\node_modules\react-native-audio-playback\android * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 24s.
info Run CLI with --verbose flag for more details.
npm verb exit 1
npm verb code 1

```

**Comment by itsramiel** [comment]
@Akash-Pavithran can you please try using `react-native-audio-playback@1.0.5-beta.0`? I believe it should resolve the error you encountered now and the lib will be able to support older versions.

**Comment by Akash-Pavithran** [comment]
@itsramiel I can confirm that the app builds successfully and i was able to load and play sound in:
```bash
"react-native": "0.73.11",
    "react-native-audio-playback": "^1.0.5-beta.0"
```
However in 0.72 it still fails (maybe due to the issues you mentioned). 
So from 0.73 onwards this works - also 0.73 has kotlin support so you dont need to add codes in build.gradle files

**Comment by itsramiel** [comment]
Hi @Akash-Pavithran,

Thank you for your patience and for checking the issue! Yes for 0.72 it wont work unless you add support for kotlin. I will create a release soon. For now I will close the issue.
